### ISSUE TITLE
Suggested way to edit HTML?

### ISSUE THREAD

**Issue by swetepete** [oguzhanuyanik-sr/bilingual-reading#1]
Cool tool but how do you suggest we edit the HTML? I open it in VS Code, the tags are all clumped together:

`Albert</li></ul><ul class="line"><li class='item-one notranslate'>Campbell</li><li class='item-two'>Campbell</li></ul><ul class="line"><li class='item-one notranslate'>(*</li><li class='item-two'>(*</li></ul><ul class="line"><li class='item-one notranslate'>10</li><li class='item-two'>10</li></ul><p class='text-one notranslate'> August 1910 in Leiters Ford, Indiana; † 15</p><p class='text-two'> August 1910 in Leiters Ford, Indiana; † 15</p><ul class="line">`

I might try to find an extension that separates the HTML onto separate lines. Even then it would be better to have an application that provides a convenient interface for editing the HTML fields, like just blank texts fields you could click on and enter the text.

Thanks

**Comment by oguzhanuyanik-sr** [comment]
Thank you for your comment. Since I did not foresee the need for editing the downloaded files, I did not make any development in this direction. Have you tried formatting with the Beautify plugin in VS Code?
